admin_portada:
    path: /
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminDeclaracionjurada:listar }
    
admin_declaraciones_listar:
    path: /declaracion/listar
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminDeclaracionjurada:listar }  
    
admin_jubidat:
    path:     /declaracion/jubidat/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminDeclaracionjurada:getJubidat }     
    requirements:
        id: \d+    

admin_jubi1ind:
    path:     /declaracion/jubi1ind/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminDeclaracionjurada:getJubi1ind }     
    requirements:
        id: \d+    

admin_mostrar_totales:
    path:     /declaracion/totales/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminDeclaracionjurada:mostrarTotales } 
    requirements:
        id: \d+    
    
admin_declaracion_aprobar:
    path:     /declaracion/aprobar/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminDeclaracionjurada:aprobarDeclaracion }
    requirements:
        id: \d+    
    
admin_declaracion_rechazar:
    path:     /declaracion/rechazar/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminDeclaracionjurada:rechazarDeclaracion }
    requirements:
        id: \d+    
  
admin_representante_listar:
    path:     /representante/listar
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminRepresentante:listar } 

admin_representante_ver:
    path:     /representante/ver/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminRepresentante:ver } 
    requirements:
        id: \d+  
        
admin_organismo_listar:
    path:     /organismo/listar
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminOrganismo:listar } 

admin_organismo_ver:
    path:     /organismo/ver/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminOrganismo:ver } 
    requirements:
        id: \d+          
    
admin_organismo_declaraciones_por_organismo:
    path: /organismo/{id}/ddjj
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminOrganismo:listarDeclaracionesPorOrganismo }    

    