organismo_declaracion_listar:
    path:     /declaracion/listar
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:index }

organismo_declaracion_listar_pdf:
    path:     /declaracion/listarPdf
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:listarPdf }

organismo_declaracion_ver:
    path:     /declaracion/ver/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:ver }
    requirements:
        id: \d+

organismo_declaracion_prueba:
    path:     /declaracion/prueba
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:prueba }

organismo_declaracion_nuevo:
    path:     /declaracion/nuevo
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:nuevo }

organismo_declaracion_editar:
    path:     /declaracion/editar/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:editar }
    requirements:
        id: \d+

organismo_declaracion_borrar:
    path:     /declaracion/borrar/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:borrar }
    requirements:
        id: \d+

organismo_declaracion_error:
    path:     /declaracion/error/{error}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:error }

organismo_organismo_listar:
    path:     /detalle
    defaults: { _controller: JubilacionesDeclaracionesBundle:Organismo:detalles }

organismo_organismo_editar:
    path:     /organismo/editar
    defaults: { _controller: JubilacionesDeclaracionesBundle:Organismo:modificar }

organismo_organismo_ver:
    path:     /organismo/ver/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Organismo:ver }
    requirements:
        id: \d+

organismo_representante_nuevo:
    path:     /representante/nuevo
    defaults: { _controller: JubilacionesDeclaracionesBundle:Representante:nuevo }

organismo_representante_editar:
    path:     /representante/editar
    defaults: { _controller: JubilacionesDeclaracionesBundle:Representante:editar }

organismo_representante_ver:
    path:     /representante/ver/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Representante:ver }

organismo_representante_desvincular:
    path:     /representante/desvincular
    defaults: { _controller: JubilacionesDeclaracionesBundle:Representante:desvincular }

organismo_representante_existente:
    path:     /representante/{cuil}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Representante:mostrarRepresentanteExistente }

organismo_representante_existente_vincular:
    path:     /representante/vincular/{cuil}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Representante:vincular }

organismo_convenio_cuota_listar:
    path:     /conveniocuota/listar
    defaults: { _controller: JubilacionesDeclaracionesBundle:Conveniocuota:listar }

organismo_convenio_cuota_ver:
    path:     /conveniocuota/ver/{codigo_convenio}/{tramo}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Conveniocuota:ver }
    requirements:
        id: \d+

organismo_convenio_imprimir_boleta:
    path:     /conveniocuota/imprimir/{codigo_convenio}/{tramo}/{cuota}/{vencimiento}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Conveniocuota:boletaPdf }
    requirements:
        id: \d+

organismo_usuario_editar:
    path:     /usuario/editar
    defaults: { _controller: JubilacionesDeclaracionesBundle:Usuario:editarOrganismo }
