registrar_representante:
    path: /representante/nuevo
    defaults: { _controller: JubilacionesDeclaracionesBundle:Default:nuevoRepresentante }     
  
organismo_declaracion_listar:
    path:     /declaracion/listar
    defaults: { _controller: JubilacionesDeclaracionesBundle:OrganismoDeclaracionjurada:listar }
    
organismo_declaracion_ver:
    path:     /declaracion/ver/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:OrganismoDeclaracionjurada:ver } 
    requirements:
        id: \d+    
    
organismo_declaracion_nuevo:
    path:     /declaracion/nuevo
    defaults: { _controller: JubilacionesDeclaracionesBundle:OrganismoDeclaracionjurada:nuevo } 
    
organismo_declaracion_editar:
    path:     /declaracion/editar/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:OrganismoDeclaracionjurada:editar }
    requirements:
        id: \d+

organismo_declaracion_borrar:
    path:     /declaracion/borrar/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:OrganismoDeclaracionjurada:borrar }
    requirements:
        id: \d+

organismo_declaracion_error:    
    path:     /declaracion/error/{error}
    defaults: { _controller: JubilacionesDeclaracionesBundle:OrganismoDeclaracionjurada:error }
    
