organismo_declaracion_listar:
    path:     /declaracion/listar
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:listar }
    
organismo_declaracion_ver:
    path:     /declaracion/ver/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:ver } 
    requirements:
        id: \d+    
    
organismo_declaracion_nuevo:
    path:     /declaracion/nuevo
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:nuevo } 
    
organismo_declaracion_editar:
    path:     /declaracion/editar/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:editar }
    requirements:
        id: \d+

organismo_declaracion_borrar:
    path:     /declaracion/borrar/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:borrar }
    requirements:
        id: \d+

    

