organismo_declaraciones_juradas:
    path:     /declaraciones
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:declaraciones }
    
organismo_declaracion_jurada:
    path:     /declaracion/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:declaracion } 
    requirements:
        id: \d+
    
organismo_declaracion_nuevo:
    path:     /declaracion/nuevo
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:nuevo }     

organismo_declaracion_borrar:
    path:     /declaracion/borrar/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:borrar }     

organismo_mostrar_totales:
    path:     /declaracion/totales/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:mostrarTotales } 
    
organismo_declaracion_jubidat:
    path:     /declaracion/jubidat/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:getJubidat }     
