organismo_declaraciones_juradas:
    path:     /declaraciones
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:listar }
    
organismo_declaracion_jurada:
    path:     /declaracion/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Declaracionjurada:declaracion }    
