inicio:
    path: /
    defaults: { _controller: JubilacionesDeclaracionesBundle:Default:index }

login:
    path: /login
    defaults: { _controller: JubilacionesDeclaracionesBundle:Login:login }

login_check:
    path: /login_check
    
logout:
    path: /logout
    
estatica:
    path: /sitio/{pagina}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Default:estatica } 

registrar_representante:
    path: /representante/nuevo
    defaults: { _controller: JubilacionesDeclaracionesBundle:Default:nuevoRepresentante }  
    
principal_logueado:
    path: /principal
    defaults: { _controller: JubilacionesDeclaracionesBundle:Default:principal }
  