admin_portada:
    path: /
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminDeclaracionjurada:listar }
    
admin_declaraciones_listar:
    path: /declaracion/listar
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminDeclaracionjurada:listar }   

admin_jubidat:
    path:     /declaracion/jubidat/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminDeclaracionjurada:getJubidat }     

admin_jubi1ind:
    path:     /declaracion/jubi1ind/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminDeclaracionjurada:getJubi1ind }     

admin_mostrar_totales:
    path:     /declaracion/totales/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminDeclaracionjurada:mostrarTotales } 
    
admin_declaracion_aprobar:
    path:     /declaracion/aprobar/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminDeclaracionjurada:aprobarDeclaracion }
    
admin_declaracion_rechazar:
    path:     /declaracion/rechazar/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminDeclaracionjurada:rechazarDeclaracion }
        