inicio:
    path: /
    defaults: { _controller: JubilacionesDeclaracionesBundle:Default:index }

login:
    path: /login
    defaults: { _controller: JubilacionesDeclaracionesBundle:Login:login }

login_check:
    path: /login_check

logout:
    path: /logout

politicas:
    path: /politicas
    defaults: { _controller: JubilacionesDeclaracionesBundle:Default:estatica }

registrar_rep:
    path: /representante/nuevo
    defaults: { _controller: JubilacionesDeclaracionesBundle:Default:nuevoRepresentante }

representante_ver:
    path: /representante/ver/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:Default:verRepresentante }
    requirements:
        id: \d+
        
principal_logueado:
    path: /principal
    defaults: { _controller: JubilacionesDeclaracionesBundle:Default:principal }
