admin_usuario_listar:
    path: /usuario/listar
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminUsuario:listar }

admin_usuario_nuevo:
    path: /usuario/nuevo
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminUsuario:nuevo }

admin_importacion_listar:
    path: /importacion/listar
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminImportacion:listar }

admin_importacion_nuevo:
    path: /importacion/nuevo
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminImportacion:nuevo }

admin_importacion_subir:
    path: /importacion/subir/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminImportacion:importar }

admin_importacion_borrar:
    path: /importacion/borrar/{id}
    defaults: { _controller: JubilacionesDeclaracionesBundle:AdminImportacion:borrar }
