jubilaciones_declaraciones:
    resource: "@JubilacionesDeclaracionesBundle/Resources/config/routing.yml"
    prefix:   /

jubilaciones_declaraciones_contralor:
    resource: "@JubilacionesDeclaracionesBundle/Resources/config/routing-contralor.yml"
    prefix:   /contralor 
    
jubilaciones_admin:
    resource: "@JubilacionesDeclaracionesBundle/Resources/config/routing-admin.yml"
    prefix:   /admin 
   
app:
    resource: '@AppBundle/Controller/'
    type: annotation
