# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Jubilaciones\DeclaracionesBundle\Entity\User:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    role_hierarchy:
        ROLE_ADMIN: [ROLE_CONTRALOR,ROLE_ORGANISMO,ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALOWED_TO_SWITCH]
        
    providers:
        usuarios_db:
            entity:
                class: JubilacionesDeclaracionesBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer    

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            provider: usuarios_db
            form_login:
                login_path: login
                check_path: login_check
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
                # por defecto, esta funcionalidad está disponible en una
                # checkbox en el formulario de login, descomenta la
                # siguiente línea para activarlo siempre.
                #always_remember_me: true    
            logout:
                path: /logout
                target: /

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
        default:
            anonymous: ~
            http_basic: ~

    access_control:
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: '^/principal', roles: ['ROLE_ORGANISMO'] }
        
        #- { path: '^/contralor', roles: ROLE_CONTRALOR }
        #- { path: '^/organismo', roles: ROLE_ORGANISMO }
        
        
