# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        Jubilaciones\DeclaracionesBundle\Entity\User:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        our_db_provider:
            entity:
                class: Jubilaciones\DeclaracionesBundle:User
                property: username
                # if you're using multiple entity managers
                # manager_name: customer    

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: our_db_provider
            form_login:
                login_path: /login
                check_path: /login
                default_target_path: organismo_declaracion_listar
            logout:
                path: /logout/
                target: /

    access_control:
            - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: '^/contralor', roles: ROLE_ADMIN }
            - { path: '^/', roles: ROLE_USER }