<?php

namespace Jubilaciones\DeclaracionesBundle\Repository;

/**
 * DeclaracionjuradaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeclaracionjuradaRepository extends \Doctrine\ORM\EntityRepository
{
}
