<?php

namespace Jubilaciones\DeclaracionesBundle\Repository;

/**
 * RepresentanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepresentanteRepository extends \Doctrine\ORM\EntityRepository
{
}
